/-
  Reflexive Architecture — cross-cutting synthesis (NEMS · APS · Infinity Compression).
  Apex program: layered interfaces + integrated architecture theorems.
-/

import ReflexiveArchitecture.Outer.Interface
import ReflexiveArchitecture.Outer.SemanticRemainder
import ReflexiveArchitecture.Middle.Interface
import ReflexiveArchitecture.Middle.CompositionExactness
import ReflexiveArchitecture.Inner.Interface
import ReflexiveArchitecture.Inner.ResiduePackage
import ReflexiveArchitecture.Universal.ReflectiveCertificationSystem
import ReflexiveArchitecture.Universal.FiberBasics
import ReflexiveArchitecture.Universal.ExhaustionDefinitions
import ReflexiveArchitecture.Universal.SectionsAndObstructions
import ReflexiveArchitecture.Universal.AbstractSummit
import ReflexiveArchitecture.Universal.ConditionalUniversality
import ReflexiveArchitecture.Universal.StrongProgram
import ReflexiveArchitecture.Universal.SummitProgram
import ReflexiveArchitecture.Universal.ResidualProgram
import ReflexiveArchitecture.Bridge.Architecture
import ReflexiveArchitecture.Bridge.LayeredTheorem
import ReflexiveArchitecture.Bridge.CollapsePredicates
import ReflexiveArchitecture.Bridge.StratifiedNonCollapse
import ReflexiveArchitecture.Bridge.BareCanonicityNotReflectiveFinality
import ReflexiveArchitecture.Bridge.GluingRouteCoherence
import ReflexiveArchitecture.Bridge.SemanticRemainderToEnrichedGap
import ReflexiveArchitecture.Bridge.NonErasurePrinciple
import ReflexiveArchitecture.Bridge.LinkedArchitecture
import ReflexiveArchitecture.Instances.ToyCombinedInstance
import ReflexiveArchitecture.Instances.FromAPS
import ReflexiveArchitecture.Instances.FromNEMS
import ReflexiveArchitecture.Instances.FromIC
import ReflexiveArchitecture.Instances.ConcreteArchitecture
import ReflexiveArchitecture.Instances.CrossCorpusInstance
import ReflexiveArchitecture.Instances.ConcreteFromNEMS
import ReflexiveArchitecture.Instances.ConcreteFromIC
import ReflexiveArchitecture.Bridge.DirectCrossCorpusBridge
import ReflexiveArchitecture.Bridge.SharedReflexiveArchitecture
import ReflexiveArchitecture.Bridge.UniversalNonErasureLaw
import ReflexiveArchitecture.Bridge.NecessityTheorem

namespace ReflexiveArchitecture

/-- Root: EPIC_015–018 complete; EPIC_019 universal layer + EPIC_020 `StrongProgram` + EPIC_021 `SummitProgram` + EPIC_022 `ResidualProgram` imported. -/
def apex001Root := ()

end ReflexiveArchitecture
